// 🔒 AUTO-GENERATED FILE — DO NOT EDIT
// Generated by next-typed-routes on 2025-07-26T15:49:32.113Z

export type AppRoute =
  | never;

// Route templates for runtime validation
const routeTemplates: AppRoute[] = [
  "/",
  "/about",
  "/home",
  "/user/[id]",
  "/user/[id]/posts/[postId]"
];

// Runtime validation function
export function isValidRoute(path: string): boolean {
  return routeTemplates.some((template) => {
    const regexStr = "^" + template.replace(/\[.+?\]/g, "[^/]+") + "$";
    return new RegExp(regexStr).test(path);
  });
}
