// 🔒 AUTO-GENERATED FILE — DO NOT EDIT
// Generated by next-typed-routes on 2025-07-26T19:56:15.882Z

// Re-export all types from generated files
export type { AppRoute, TypedRoute } from "./generated/routes";
export { allRoutes } from "./generated/routes";

// Re-export runtime utilities from the library
export { route } from "next-typed-routes";

// Runtime validation function using generated routes
import { allRoutes } from "./generated/routes";

/**
 * Validate if a given path matches any of the defined routes
 * @param path - The path to validate
 * @returns true if the path matches a defined route pattern
 */
export function isValidRoute(path: string): boolean {
  return allRoutes.some((template) => {
    const regexStr = "^" + template.replace(/\[.+?\]/g, "[^/]+") + "$";
    return new RegExp(regexStr).test(path);
  });
}

/**
 * Get all available routes
 * @returns Array of all route templates
 */
export function getAllRoutes(): readonly string[] {
  return allRoutes;
}
